### ISSUE TITLE
new_model params and pretrained_model params have different value initially.

### ISSUE THREAD

**Issue by shujaatHusn** [Sanyuan-Chen/RecAdam#16]
Hi,

When new_model and pretrained_model are defined, [here](https://github.com/Sanyuan-Chen/RecAdam/blob/master/run_glue_with_RecAdam.py#L755) and [here](https://github.com/Sanyuan-Chen/RecAdam/blob/master/run_glue_with_RecAdam.py#L769), they have the same value.

But [here](https://github.com/Sanyuan-Chen/RecAdam/blob/master/run_glue_with_RecAdam.py#L152), params and pretrain_params have different values. I cannot figure out how did they become different. I was wondering if anyone could offer any insight?

I stepped into run_glue_with_recadam.py in PyCharm and monitored the values in the debugger.

**Comment by Sanyuan-Chen** [comment]
Hi~ Since the new_model is randomly initialized and the pretrained_model is initialized with the pretrained model, they should have different initialization values when they are defined.  
Also, please notice whether the values you monitor are part of the pretrained model or the additional output layer. The additional output layers of both the new_model  and the pretrained_model are randomly initialized since it is excluded in the parameters of pretrained LMs.
