### ISSUE TITLE
Doubt about PretrainModel and NewModel in the implementation

### ISSUE THREAD

**Issue by Shashi456** [Sanyuan-Chen/RecAdam#4]
In the line:
https://github.com/Sanyuan-Chen/RecAdam/blob/0b00acef0bacc96813d510e1ecb3ad519a055660/run_glue_with_RecAdam.py#L154

What does n, p stand for ? 

and when you do the following in the finetuning case:
https://github.com/Sanyuan-Chen/RecAdam/blob/0b00acef0bacc96813d510e1ecb3ad519a055660/run_glue_with_RecAdam.py#L775

Does that mean for finetuning with some additional classification module on top of the model, you maintain both the new_model and a pretrained model in the VRAM of the GPU?

**Comment by Sanyuan-Chen** [comment]
Hi~

1. n, p stand for the name and the tensor of each parameter in the model. You can refer to the PyTorch docs for more details: https://pytorch.org/docs/stable/nn.html#torch.nn.Module.named_parameters

2. Yes, we load both the fine-tuning model and the pretrained model in GPU, because we can only operate two tensor objects when they are in the same device. Alternatively, you can load the pretrained model to CPU initially, and temporarily transfer a parameter to GPU when necessary. It would save some GPU memory but would cost more time because of the frequent transfer between CPU and GPU.

We note that we update all the parameters (both the pretrained modules and the additional classification modules) of the fine-tuning model, and we don't need to update the parameters of the pretrained model.
